:experimental:

[id="create-a-new-physical-partition_{context}"]
= Create a new Physical partition

Create a new 100MB Physical partition mounted under /mountpoint

.Procedure
. List the partition table.
+
----
# fdisk -l
----
+
The output returns:
+
[subs=+quotes]
----
Disk /dev/vda: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf8017de9

Device     Boot   Start      End  Sectors Size Id Type
/dev/vda1  *       2048  2099199  2097152   1G 83 Linux
/dev/vda2       2099200 41943039 39843840  19G 8e Linux LVM


*Disk /dev/vdb: 10.7 GiB, 11489038336 bytes, 22439528 sectors*
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
----

. Select the device.
+
----
# fdisk /dev/vdb
----
+
The output returns:
+
----
Welcome to fdisk (util-linux 2.32.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help):
----
. Press btn:[m] to see the shortcuts.
+
The output returns:
+
----
Help:

  DOS (MBR)
   a   toggle a bootable flag
   b   edit nested BSD disklabel
   c   toggle the dos compatibility flag

  Generic
   d   delete a partition
   F   list free unpartitioned space
   l   list known partition types
   n   add a new partition
   p   print the partition table
   t   change a partition type
   v   verify the partition table
   i   print information about a partition

  Misc
   m   print this menu
   u   change display/entry units
   x   extra functionality (experts only)

  Script
   I   load disk layout from sfdisk script file
   O   dump disk layout to sfdisk script file

  Save & Exit
   w   write table to disk and exit
   q   quit without saving changes

  Create a new label
   g   create a new empty GPT partition table
   G   create a new empty SGI (IRIX) partition table
   o   create a new empty DOS partition table
   s   create a new empty Sun partition table
----

. Press btn:[n] to add a new partition.
+
The output returns:
+
----
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
----
. Press btn:[e] to add a new extended partition.
+
The output returns:
+
----
Partition number (1-4, default 1):
----
+
. Press btn:[Enter] to select the default option.
+
The output returns:
+
----
First sector (2048-41943039, default 2048):
----
. Press btn:[Enter] to select the default option.
+
The output returns:
+
----
Last sector, +sectors or +size{K,M,G,T,P} (2048-22439527, default 20971519):
----
. Press btn:[Enter] to select the default option.
+
The output returns:
+
----
Created a new partition 1 of type 'Linux' and of size 10 GiB.
----
. Press btn:[n] to add a new partition.
+
The output returns:
+
----
Partition type
   p   primary (0 primary, 1 extended, 3 free)
   l   logical (numbered from 5)
Select (default p):
----
. Press btn:[l] to select the logical partition type.
+
The output returns:
+
----
Adding logical partition 5
First sector (4096-20971519, default 4096):
----
. Press btn:[Enter] to select the default option.
+
The output returns:
+
----
Last sector, +sectors or +size{K,M,G,T,P} (4096-20971519, default 20971519):
----
. Append *+100M* and press btn:[Enter].
+
[subs=+quotes]
----
Last sector, +sectors or +size{K,M,G,T,P} (4096-20971519, default 20971519): *+100M*
----
+
The output returns:
+
----
Created a new partition 5 of type 'Linux' and of size 100 MiB.
----
. Press btn:[p] to print the partition table.
+
The output returns:
+
[subs=+quotes]
----
Disk /dev/vdb: 10.7 GiB, 11489038336 bytes, 22439528 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb34bae0b

Device     Boot Start      End  Sectors  Size Id Type
/dev/vdb1        2048 20971519 20969472   10G  5 Extended
*/dev/vdb5        4096   208895   204800  100M 83 Linux*
----
. Press btn:[w] to write table to disk and exit.
+
The output returns:
+
----
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
----
. Inform the OS of partition table changes.
+
----
# partprobe
----
. Build a Linux filesystem on `/dev/vdb5`.
+
----
# mkfs.ext4 /dev/vdb5
----
+
The output returns:
+
----
mke2fs 1.44.3 (10-July-2018)
Creating filesystem with 102400 1k blocks and 25688 inodes
Filesystem UUID: aeeafeb1-73c4-4a78-89ad-54651492278e
Superblock backups stored on blocks:
	8193, 24577, 40961, 57345, 73729

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Create a directory for mounting your partition.
+
----
# mkdir /mountpoint
----
. Print block device attributes.
+
----
# blkid
----
+
The output returns:
+
[subs=+quotes]
----
/dev/mapper/rhel-root: UUID="87d62757-c017-490a-be4a-e9533dd644be" TYPE="xfs"
/dev/vda2: UUID="mAdV56-WOQU-CV0W-dWpp-FCgd-VAqD-z5cV84" TYPE="LVM2_member" PARTUUID="f8017de9-02"
/dev/vda1: UUID="e292df87-d3d5-4199-bf01-5dbea1a59c05" TYPE="xfs" PARTUUID="f8017de9-01"
*/dev/vdb5: UUID="aeeafeb1-73c4-4a78-89ad-54651492278e" TYPE="ext4" PARTUUID="b34bae0b-05"*
/dev/mapper/rhel-swap: UUID="e851aa0b-638e-4a39-b05a-11fb253dfa2e" TYPE="swap"
----
. Copy the *UUID*.
. Open `/etc/fstab`.
+
----
# vim /etc/fstab
----
. Edit the `fstab`.
+
[subs=+quotes]
----
#
# /etc/fstab
# Created by anaconda on Mon Sep 28 01:46:30 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
#
# After editing this file, run 'systemctl daemon-reload' to update systemd
# units generated from this file.
#
/dev/mapper/rhel-root   /                       xfs     defaults        0 0
UUID=e292df87-d3d5-4199-bf01-5dbea1a59c05 /boot                   xfs     defaults        0 0
/dev/mapper/rhel-swap   swap                    swap    defaults        0 0
*UUID=aeeafeb1-73c4-4a78-89ad-54651492278e /mountpoint ext4 defaults 0 0*
----
. Save and exit.
. Mount all filesystems.
+
----
# mount -a
----

.Verification steps
* Verify the existence of your partition.
+
----
# fdisk -l
----
+
The output returns:
+
[subs=+quotes]
----
Device     Boot Start      End  Sectors  Size Id Type
/dev/vdb1        2048 20971519 20969472   10G  5 Extended
*/dev/vdb5        4096   208895   204800  100M 83 Linux*
----
