

[id="reset-root-passwd-on-boot_{context}"]
= Reset `root` password on boot

.Procedure
. Reboot the system.

. Press btn:[e] on the GRUB 2 boot screen to interrupt the boot process.
+
The kernel boot parameters appear.
+
[subs=+quotes]
----
load_video
set gfx_payload=keep
insmod gzio
linux ($root)/vmlinuz-4.18.0-80.e18.x86_64 root=/dev/mapper/rhel-root ro crash\
kernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv/swap rhab quiet
initrd ($root)/initramfs-4.18.0-80.e18.x86_64.img $tuned_initrd
----

. Go to the start of the line that starts with *linux*. Press btn:[Ctrl+e] to jump to the end of the line.
+
[subs=+quotes]
----
*linux* ($root)/vmlinuz-4.18.0-80.e18.x86_64 root=/dev/mapper/rhel-root ro crash\
kernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv/swap rhab quiet
----

. Add `rd.break` to the end of the line that starts with `linux`.
+
[subs=+quotes]
----
*linux* ($root)/vmlinuz-4.18.0-80.e18.x86_64 root=/dev/mapper/rhel-root ro crash\
kernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv/swap rhab quiet *rd.break*
----

. Press btn:[Ctrl+x] to start the system with the changed parameters.
+
The `switch_root` prompt appears.

. Remount the file system as writable:
+
[subs=+quotes]
----
mount -o remount,rw /sysroot
----
+
The file system is mounted as read-only in the `/sysroot` directory. Remounting the file system as writable allows you to change the password.

. Enter the `chroot` environment:
+
[subs=+quotes]
----
chroot /sysroot
----
+
The `sh-4.4#` prompt appears.

. Reset the `root` password:
+
[subs=+quotes]
----
passwd
----
+
Follow the instructions displayed by the command line to finalize the change of the `root` password.

. Enable the SELinux relabeling process on the next system boot:
+
----
touch /.autorelabel
----

. Exit the `chroot` environment:
+
----
exit
----

. Exit the `switch_root` prompt:
+
----
exit
----

. Wait until the SELinux relabeling process is finished. Note that relabeling a large disk might take a long time. The system reboots automatically when the process is complete.
